; JamesDSP Controller package default.

[General]
postGain = 0

[BassBoost]
enabled = false
gain = 0

[StereoWide]
enabled = false
level = 0

[Reverb]
enabled = false
preset = 0

[Tube]
enabled = false
gain = 0

[Compressor]
enabled = false
granularity = 1
timeConstant = 0.56
resolution = 0
gains = 0,0,0,0,0,0,0

[Equalizer]
enabled = false
mode = 0
interpolation = 0
gains = 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

[Crossfeed]
enabled = false
mode = 0

[DDC]
enabled = false
file =

[Convolver]
enabled = false
file =

[Darwin]
enabled = false
package =
filter =
impulseFile =
harmonic = 0
autoHeadroom = true

[LiveProg]
enabled = false
file =
